# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 530)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 861, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.label_filters_input = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_input.setGeometry(QtCore.QRect(200, 30, 301, 261))
        self.label_filters_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input.setObjectName("label_filters_input")
        self.label_filters_output = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_output.setGeometry(QtCore.QRect(510, 30, 301, 261))
        self.label_filters_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output.setObjectName("label_filters_output")
        self.pushButton_filters_load = QtWidgets.QPushButton(self.tab_filters)
        self.pushButton_filters_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_filters_load.setObjectName("pushButton_filters_load")
        self.label = QtWidgets.QLabel(self.tab_filters)
        self.label.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_filters)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 801, 111))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 321, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 20, 321, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 20, 321, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.label_histograms_houtput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_houtput.setGeometry(QtCore.QRect(560, 220, 281, 231))
        self.label_histograms_houtput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_houtput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_houtput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_houtput.setObjectName("label_histograms_houtput")
        self.pushButton_histograms_load = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_histograms_load.setGeometry(QtCore.QRect(40, 20, 121, 81))
        self.pushButton_histograms_load.setObjectName("pushButton_histograms_load")
        self.label_histograms_input = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_input.setGeometry(QtCore.QRect(270, 0, 281, 211))
        self.label_histograms_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input.setObjectName("label_histograms_input")
        self.label_histograms_output = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_output.setGeometry(QtCore.QRect(560, 0, 281, 211))
        self.label_histograms_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output.setObjectName("label_histograms_output")
        self.label_10 = QtWidgets.QLabel(self.tab_histograms)
        self.label_10.setGeometry(QtCore.QRect(50, 160, 71, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_histograms)
        self.label_11.setGeometry(QtCore.QRect(50, 130, 71, 21))
        self.label_11.setObjectName("label_11")
        self.label_histograms_hinput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_hinput.setGeometry(QtCore.QRect(270, 220, 281, 231))
        self.label_histograms_hinput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput.setObjectName("label_histograms_hinput")
        self.pushButton = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 161, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 240, 161, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 280, 161, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 320, 161, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_histograms)
        self.comboBox_3.setGeometry(QtCore.QRect(40, 360, 161, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.tabWidget.addTab(self.tab_histograms, "")
        self.tab_hybrid = QtWidgets.QWidget()
        self.tab_hybrid.setObjectName("tab_hybrid")
        self.label_histograms_input_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_input_2.setGeometry(QtCore.QRect(200, 20, 221, 161))
        self.label_histograms_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_2.setObjectName("label_histograms_input_2")
        self.label_histograms_hinput_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_hinput_2.setGeometry(QtCore.QRect(200, 190, 221, 161))
        self.label_histograms_hinput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_2.setObjectName("label_histograms_hinput_2")
        self.label_histograms_output_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_output_2.setGeometry(QtCore.QRect(430, 20, 391, 331))
        self.label_histograms_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_2.setObjectName("label_histograms_output_2")
        self.label_12 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.label_12.setObjectName("label_12")
        self.pushButton_histograms_load_2 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_2.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.pushButton_histograms_load_2.setObjectName("pushButton_histograms_load_2")
        self.label_13 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_13.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_14.setGeometry(QtCore.QRect(30, 310, 71, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_15.setGeometry(QtCore.QRect(30, 290, 71, 21))
        self.label_15.setObjectName("label_15")
        self.pushButton_histograms_load_3 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_3.setGeometry(QtCore.QRect(20, 200, 121, 81))
        self.pushButton_histograms_load_3.setObjectName("pushButton_histograms_load_3")
        self.pushButton_histograms_load_4 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_4.setGeometry(QtCore.QRect(20, 370, 141, 61))
        self.pushButton_histograms_load_4.setObjectName("pushButton_histograms_load_4")
        self.tabWidget.addTab(self.tab_hybrid, "")
        self.tab_Hough = QtWidgets.QWidget()
        self.tab_Hough.setObjectName("tab_Hough")
        self.label_31 = QtWidgets.QLabel(self.tab_Hough)
        self.label_31.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.label_31.setObjectName("label_31")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_Hough)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 340, 831, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(450, 20, 321, 81))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_9)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.label_6.setObjectName("label_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_6.setGeometry(QtCore.QRect(150, 30, 71, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_3.setGeometry(QtCore.QRect(280, 50, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        self.label_37.setGeometry(QtCore.QRect(10, 50, 90, 16))
        self.label_37.setObjectName("label_37")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox.setGeometry(QtCore.QRect(150, 50, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_filters_output_4 = QtWidgets.QLabel(self.tab_Hough)
        self.label_filters_output_4.setGeometry(QtCore.QRect(510, 30, 311, 271))
        self.label_filters_output_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output_4.setObjectName("label_filters_output_4")
        self.pushButton_hough_load = QtWidgets.QPushButton(self.tab_Hough)
        self.pushButton_hough_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_hough_load.setObjectName("pushButton_hough_load")
        self.label_filters_input_4 = QtWidgets.QLabel(self.tab_Hough)
        self.label_filters_input_4.setGeometry(QtCore.QRect(200, 30, 301, 271))
        self.label_filters_input_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input_4.setObjectName("label_filters_input_4")
        self.label_36 = QtWidgets.QLabel(self.tab_Hough)
        self.label_36.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label_36.setObjectName("label_36")
        self.Apply_Hough = QtWidgets.QPushButton(self.tab_Hough)
        self.Apply_Hough.setGeometry(QtCore.QRect(30, 210, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Apply_Hough.setFont(font)
        self.Apply_Hough.setAutoFillBackground(False)
        self.Apply_Hough.setStyleSheet("")
        self.Apply_Hough.setObjectName("Apply_Hough")
        self.tabWidget.addTab(self.tab_Hough, "")
        self.tab_Harris = QtWidgets.QWidget()
        self.tab_Harris.setObjectName("tab_Harris")
        self.label_filters_input_5 = QtWidgets.QLabel(self.tab_Harris)
        self.label_filters_input_5.setGeometry(QtCore.QRect(220, 30, 311, 271))
        self.label_filters_input_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input_5.setObjectName("label_filters_input_5")
        self.label_filters_output_5 = QtWidgets.QLabel(self.tab_Harris)
        self.label_filters_output_5.setGeometry(QtCore.QRect(540, 30, 301, 271))
        self.label_filters_output_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output_5.setObjectName("label_filters_output_5")
        self.label_39 = QtWidgets.QLabel(self.tab_Harris)
        self.label_39.setGeometry(QtCore.QRect(30, 140, 141, 21))
        self.label_39.setObjectName("label_39")
        self.pushButton_harris_load = QtWidgets.QPushButton(self.tab_Harris)
        self.pushButton_harris_load.setGeometry(QtCore.QRect(20, 30, 121, 71))
        self.pushButton_harris_load.setObjectName("pushButton_harris_load")
        self.label_34 = QtWidgets.QLabel(self.tab_Harris)
        self.label_34.setGeometry(QtCore.QRect(30, 170, 141, 21))
        self.label_34.setObjectName("label_34")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_Harris)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 330, 791, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_13.setGeometry(QtCore.QRect(450, 30, 321, 81))
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 20, 351, 91))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_44 = QtWidgets.QLabel(self.groupBox_12)
        self.label_44.setGeometry(QtCore.QRect(30, 30, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_12)
        self.textEdit_5.setGeometry(QtCore.QRect(190, 30, 104, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_45 = QtWidgets.QLabel(self.groupBox_12)
        self.label_45.setGeometry(QtCore.QRect(20, 50, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_12)
        self.label_46.setGeometry(QtCore.QRect(40, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_Harris)
        self.comboBox_6.setGeometry(QtCore.QRect(30, 260, 121, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_43 = QtWidgets.QLabel(self.tab_Harris)
        self.label_43.setGeometry(QtCore.QRect(10, 240, 191, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.tabWidget.addTab(self.tab_Harris, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(30, 150, 151, 21))
        self.label_40.setObjectName("label_40")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(30, 180, 151, 21))
        self.label_35.setObjectName("label_35")
        self.pushButton_snake_load = QtWidgets.QPushButton(self.tab)
        self.pushButton_snake_load.setGeometry(QtCore.QRect(20, 40, 121, 81))
        self.pushButton_snake_load.setObjectName("pushButton_snake_load")
        self.label_histograms_output_3 = QtWidgets.QLabel(self.tab)
        self.label_histograms_output_3.setGeometry(QtCore.QRect(210, 20, 621, 271))
        self.label_histograms_output_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_3.setText("")
        self.label_histograms_output_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_3.setObjectName("label_histograms_output_3")
        self.Apply_Harris_2 = QtWidgets.QPushButton(self.tab)
        self.Apply_Harris_2.setGeometry(QtCore.QRect(20, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Apply_Harris_2.setFont(font)
        self.Apply_Harris_2.setAutoFillBackground(False)
        self.Apply_Harris_2.setStyleSheet("")
        self.Apply_Harris_2.setObjectName("Apply_Harris_2")
        self.Apply_Harris_3 = QtWidgets.QPushButton(self.tab)
        self.Apply_Harris_3.setGeometry(QtCore.QRect(20, 330, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Apply_Harris_3.setFont(font)
        self.Apply_Harris_3.setAutoFillBackground(False)
        self.Apply_Harris_3.setStyleSheet("")
        self.Apply_Harris_3.setObjectName("Apply_Harris_3")
        self.Apply_Harris_4 = QtWidgets.QPushButton(self.tab)
        self.Apply_Harris_4.setGeometry(QtCore.QRect(20, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Apply_Harris_4.setFont(font)
        self.Apply_Harris_4.setAutoFillBackground(False)
        self.Apply_Harris_4.setStyleSheet("")
        self.Apply_Harris_4.setObjectName("Apply_Harris_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(200, 300, 291, 151))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(10, 80, 31, 16))
        self.label_38.setObjectName("label_38")
        self.label_41 = QtWidgets.QLabel(self.groupBox_11)
        self.label_41.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_11)
        self.label_42.setGeometry(QtCore.QRect(10, 120, 51, 21))
        self.label_42.setObjectName("label_42")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_11)
        self.textEdit.setGeometry(QtCore.QRect(70, 30, 51, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_11)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 70, 51, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_11)
        self.textEdit_3.setGeometry(QtCore.QRect(70, 110, 51, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_14.setGeometry(QtCore.QRect(530, 300, 301, 151))
        self.groupBox_14.setObjectName("groupBox_14")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_5.setGeometry(QtCore.QRect(140, 20, 91, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_14)
        self.textEdit_4.setGeometry(QtCore.QRect(160, 100, 61, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_14)
        self.label_5.setGeometry(QtCore.QRect(20, 99, 131, 31))
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 50, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_7.setGeometry(QtCore.QRect(80, 390, 51, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_47 = QtWidgets.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(20, 390, 51, 21))
        self.label_47.setObjectName("label_47")
        self.tabWidget.addTab(self.tab, "")
        self.tab_TM = QtWidgets.QWidget()
        self.tab_TM.setObjectName("tab_TM")
        self.label_16 = QtWidgets.QLabel(self.tab_TM)
        self.label_16.setGeometry(QtCore.QRect(20, 140, 141, 21))
        self.label_16.setObjectName("label_16")
        self.pushButton_TM_load_B = QtWidgets.QPushButton(self.tab_TM)
        self.pushButton_TM_load_B.setGeometry(QtCore.QRect(10, 250, 121, 81))
        self.pushButton_TM_load_B.setObjectName("pushButton_TM_load_B")
        self.label_17 = QtWidgets.QLabel(self.tab_TM)
        self.label_17.setGeometry(QtCore.QRect(20, 340, 141, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_TM)
        self.label_18.setGeometry(QtCore.QRect(20, 360, 141, 21))
        self.label_18.setObjectName("label_18")
        self.label_histograms_hinput_3 = QtWidgets.QLabel(self.tab_TM)
        self.label_histograms_hinput_3.setGeometry(QtCore.QRect(180, 230, 251, 211))
        self.label_histograms_hinput_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_3.setObjectName("label_histograms_hinput_3")
        self.label_histograms_input_3 = QtWidgets.QLabel(self.tab_TM)
        self.label_histograms_input_3.setGeometry(QtCore.QRect(180, 20, 251, 201))
        self.label_histograms_input_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_3.setObjectName("label_histograms_input_3")
        self.pushButton_TM_load_A = QtWidgets.QPushButton(self.tab_TM)
        self.pushButton_TM_load_A.setGeometry(QtCore.QRect(10, 50, 121, 81))
        self.pushButton_TM_load_A.setObjectName("pushButton_TM_load_A")
        self.label_19 = QtWidgets.QLabel(self.tab_TM)
        self.label_19.setGeometry(QtCore.QRect(20, 160, 141, 21))
        self.label_19.setObjectName("label_19")
        self.label_histograms_hinput_4 = QtWidgets.QLabel(self.tab_TM)
        self.label_histograms_hinput_4.setGeometry(QtCore.QRect(440, 230, 251, 211))
        self.label_histograms_hinput_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_4.setObjectName("label_histograms_hinput_4")
        self.label_histograms_input_4 = QtWidgets.QLabel(self.tab_TM)
        self.label_histograms_input_4.setGeometry(QtCore.QRect(440, 20, 251, 201))
        self.label_histograms_input_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_4.setObjectName("label_histograms_input_4")
        self.pushButton_TM_match = QtWidgets.QPushButton(self.tab_TM)
        self.pushButton_TM_match.setGeometry(QtCore.QRect(710, 280, 121, 61))
        self.pushButton_TM_match.setObjectName("pushButton_TM_match")
        self.label_20 = QtWidgets.QLabel(self.tab_TM)
        self.label_20.setGeometry(QtCore.QRect(730, 360, 91, 21))
        self.label_20.setObjectName("label_20")
        self.TM_TimeElapsed = QtWidgets.QLabel(self.tab_TM)
        self.TM_TimeElapsed.setGeometry(QtCore.QRect(730, 380, 81, 20))
        self.TM_TimeElapsed.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.TM_TimeElapsed.setText("")
        self.TM_TimeElapsed.setObjectName("TM_TimeElapsed")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_TM)
        self.groupBox_15.setGeometry(QtCore.QRect(700, 30, 141, 191))
        self.groupBox_15.setObjectName("groupBox_15")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_15)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 40, 111, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.setItemText(0, "")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.textEdit_8 = QtWidgets.QTextEdit(self.groupBox_15)
        self.textEdit_8.setGeometry(QtCore.QRect(40, 100, 71, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_15)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 81, 20))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_TM, "")
        self.tab_SIFT = QtWidgets.QWidget()
        self.tab_SIFT.setObjectName("tab_SIFT")
        self.pushButton_sift_load_B = QtWidgets.QPushButton(self.tab_SIFT)
        self.pushButton_sift_load_B.setGeometry(QtCore.QRect(10, 230, 121, 81))
        self.pushButton_sift_load_B.setObjectName("pushButton_sift_load_B")
        self.label_21 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_21.setGeometry(QtCore.QRect(20, 320, 161, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_22.setGeometry(QtCore.QRect(20, 340, 151, 21))
        self.label_22.setObjectName("label_22")
        self.pushButton_sift_load_A = QtWidgets.QPushButton(self.tab_SIFT)
        self.pushButton_sift_load_A.setGeometry(QtCore.QRect(10, 30, 121, 81))
        self.pushButton_sift_load_A.setObjectName("pushButton_sift_load_A")
        self.label_23 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_23.setGeometry(QtCore.QRect(20, 120, 151, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_24.setGeometry(QtCore.QRect(20, 140, 151, 21))
        self.label_24.setObjectName("label_24")
        self.label_histograms_output_4 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_histograms_output_4.setGeometry(QtCore.QRect(190, 220, 471, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_histograms_output_4.sizePolicy().hasHeightForWidth())
        self.label_histograms_output_4.setSizePolicy(sizePolicy)
        self.label_histograms_output_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_4.setScaledContents(False)
        self.label_histograms_output_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_4.setObjectName("label_histograms_output_4")
        self.label_histograms_hinput_5 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_histograms_hinput_5.setGeometry(QtCore.QRect(430, 10, 231, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_histograms_hinput_5.sizePolicy().hasHeightForWidth())
        self.label_histograms_hinput_5.setSizePolicy(sizePolicy)
        self.label_histograms_hinput_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_5.setScaledContents(False)
        self.label_histograms_hinput_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_5.setObjectName("label_histograms_hinput_5")
        self.label_histograms_input_5 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_histograms_input_5.setEnabled(True)
        self.label_histograms_input_5.setGeometry(QtCore.QRect(190, 10, 231, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_histograms_input_5.sizePolicy().hasHeightForWidth())
        self.label_histograms_input_5.setSizePolicy(sizePolicy)
        self.label_histograms_input_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_5.setScaledContents(False)
        self.label_histograms_input_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_5.setObjectName("label_histograms_input_5")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_SIFT)
        self.groupBox_16.setGeometry(QtCore.QRect(690, 20, 151, 171))
        self.groupBox_16.setObjectName("groupBox_16")
        self.textEdit_10 = QtWidgets.QTextEdit(self.groupBox_16)
        self.textEdit_10.setGeometry(QtCore.QRect(40, 70, 71, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_48 = QtWidgets.QLabel(self.groupBox_16)
        self.label_48.setGeometry(QtCore.QRect(20, 50, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.pushButton_sift_match = QtWidgets.QPushButton(self.tab_SIFT)
        self.pushButton_sift_match.setGeometry(QtCore.QRect(700, 280, 131, 61))
        self.pushButton_sift_match.setObjectName("pushButton_sift_match")
        self.label_25 = QtWidgets.QLabel(self.tab_SIFT)
        self.label_25.setGeometry(QtCore.QRect(720, 360, 91, 21))
        self.label_25.setObjectName("label_25")
        self.TM_TimeElapsed_2 = QtWidgets.QLabel(self.tab_SIFT)
        self.TM_TimeElapsed_2.setGeometry(QtCore.QRect(720, 380, 81, 20))
        self.TM_TimeElapsed_2.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.TM_TimeElapsed_2.setText("")
        self.TM_TimeElapsed_2.setObjectName("TM_TimeElapsed_2")
        self.tabWidget.addTab(self.tab_SIFT, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filters_input.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_filters_load.setText(_translate("MainWindow", "Load Image"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Size:"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Settings"))
        self.label_3.setText(_translate("MainWindow", "Select Filter"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Average filters"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Gaussian filter"))
        self.comboBox.setItemText(3, _translate("MainWindow", "median filter"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Sobel edge detector"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Roberts edge detector"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Prewitt edge detector"))
        self.comboBox.setItemText(7, _translate("MainWindow", "canny edge detector"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_4.setText(_translate("MainWindow", "Select Noise"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Uniform noise"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Gaussian noise"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Salt & pepper noise"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.label_histograms_houtput.setText(_translate("MainWindow", "Output Histogram"))
        self.pushButton_histograms_load.setText(_translate("MainWindow", "Load image"))
        self.label_histograms_input.setText(_translate("MainWindow", "Input image"))
        self.label_histograms_output.setText(_translate("MainWindow", "Output image"))
        self.label_10.setText(_translate("MainWindow", "Size:"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.label_histograms_hinput.setText(_translate("MainWindow", "Input Histogram"))
        self.pushButton.setText(_translate("MainWindow", "Equalization"))
        self.pushButton_2.setText(_translate("MainWindow", "Normalization"))
        self.pushButton_3.setText(_translate("MainWindow", "Local thresholding"))
        self.pushButton_4.setText(_translate("MainWindow", " Global thresholding"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "RED"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "BLUE"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "GREEN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.label_histograms_input_2.setText(_translate("MainWindow", "Input image A"))
        self.label_histograms_hinput_2.setText(_translate("MainWindow", "Input image B"))
        self.label_histograms_output_2.setText(_translate("MainWindow", "Output image"))
        self.label_12.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_2.setText(_translate("MainWindow", "Load image A"))
        self.label_13.setText(_translate("MainWindow", "Size:"))
        self.label_14.setText(_translate("MainWindow", "Size:"))
        self.label_15.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_3.setText(_translate("MainWindow", "Load image B"))
        self.pushButton_histograms_load_4.setText(_translate("MainWindow", "Make Hybrid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hybrid), _translate("MainWindow", "Hybrid"))
        self.label_31.setText(_translate("MainWindow", "Size:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Operator Settings"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Additional Tunable Parameters"))
        self.label_6.setText(_translate("MainWindow", "Enter Number of Lines:"))
        self.checkBox_3.setText(_translate("MainWindow", "Circles"))
        self.label_37.setText(_translate("MainWindow", "Select Shapes :"))
        self.checkBox.setText(_translate("MainWindow", "Lines"))
        self.label_filters_output_4.setText(_translate("MainWindow", "Output image"))
        self.pushButton_hough_load.setText(_translate("MainWindow", "Load Image"))
        self.label_filters_input_4.setText(_translate("MainWindow", "Input image"))
        self.label_36.setText(_translate("MainWindow", "Name:"))
        self.Apply_Hough.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Hough), _translate("MainWindow", "Hough"))
        self.label_filters_input_5.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output_5.setText(_translate("MainWindow", "Output image"))
        self.label_39.setText(_translate("MainWindow", "Name:"))
        self.pushButton_harris_load.setText(_translate("MainWindow", "Load Image"))
        self.label_34.setText(_translate("MainWindow", "Size:"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Operator Settings"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Edge Detector Tunable Parameters"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Operator Tunable Parameters"))
        self.label_44.setText(_translate("MainWindow", "Enter threshold value:"))
        self.label_45.setText(_translate("MainWindow", "( Thresholding technique )"))
        self.label_46.setText(_translate("MainWindow", "6000000 prefered"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Thresholding"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Local thresholding"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Non_maxima supression"))
        self.label_43.setText(_translate("MainWindow", "Corners different techniques:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Harris), _translate("MainWindow", "Harris"))
        self.label_40.setText(_translate("MainWindow", "Name:"))
        self.label_35.setText(_translate("MainWindow", "Size:"))
        self.pushButton_snake_load.setText(_translate("MainWindow", "Load Image"))
        self.Apply_Harris_2.setText(_translate("MainWindow", "Clear Anchors"))
        self.Apply_Harris_3.setText(_translate("MainWindow", "Apply"))
        self.Apply_Harris_4.setText(_translate("MainWindow", "Reset"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Countour Settings"))
        self.label_38.setText(_translate("MainWindow", "Beta"))
        self.label_41.setText(_translate("MainWindow", "Alpha"))
        self.label_42.setText(_translate("MainWindow", "Gamma"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Gradient Settings"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Filter"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Average"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Median"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Gradiant"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Sobel"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "High Pass"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Prewitt edge detector"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Canny edge detector"))
        self.label_5.setText(_translate("MainWindow", "Thershold of curvature"))
        self.pushButton_5.setText(_translate("MainWindow", "Chain Code"))
        self.label_47.setText(_translate("MainWindow", " Iteration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Active Contour"))
        self.label_16.setText(_translate("MainWindow", "Name:"))
        self.pushButton_TM_load_B.setText(_translate("MainWindow", "Load image B"))
        self.label_17.setText(_translate("MainWindow", "Name:"))
        self.label_18.setText(_translate("MainWindow", "Size:"))
        self.label_histograms_hinput_3.setText(_translate("MainWindow", "Input image B"))
        self.label_histograms_input_3.setText(_translate("MainWindow", "Input image A"))
        self.pushButton_TM_load_A.setText(_translate("MainWindow", "Load image A"))
        self.label_19.setText(_translate("MainWindow", "Size:"))
        self.label_histograms_hinput_4.setText(_translate("MainWindow", "Detected patterns"))
        self.label_histograms_input_4.setText(_translate("MainWindow", "Matching space"))
        self.pushButton_TM_match.setText(_translate("MainWindow", "Match"))
        self.label_20.setText(_translate("MainWindow", "Time Elapsed:"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Detection Parameters"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Correlation"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Zero-mean Correlation"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Sum of Squared Differences (SSD)"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Normalized Cross Correlation"))
        self.label_7.setText(_translate("MainWindow", "   Threshold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_TM), _translate("MainWindow", "Template Matching"))
        self.pushButton_sift_load_B.setText(_translate("MainWindow", "Load image B"))
        self.label_21.setText(_translate("MainWindow", "Name:"))
        self.label_22.setText(_translate("MainWindow", "Size:"))
        self.pushButton_sift_load_A.setText(_translate("MainWindow", "Load image A"))
        self.label_23.setText(_translate("MainWindow", "Name:"))
        self.label_24.setText(_translate("MainWindow", "Size:"))
        self.label_histograms_output_4.setText(_translate("MainWindow", "Features Matching"))
        self.label_histograms_hinput_5.setText(_translate("MainWindow", "Input image B"))
        self.label_histograms_input_5.setText(_translate("MainWindow", "Input image A"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Tunable Parameters"))
        self.label_48.setText(_translate("MainWindow", "Enter Sigma value:"))
        self.pushButton_sift_match.setText(_translate("MainWindow", "Match"))
        self.label_25.setText(_translate("MainWindow", "Time Elapsed:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SIFT), _translate("MainWindow", "SIFT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

